### GENERAL SETTINGS ###

# Site settings
title: UWEGAMES
description: "Games development from an elder's persepective."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/solid-jekyll" #important: start with /
url: "https://HuxyUK.github.io/solid-jekyll"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - University of the West of England,
    - Frenchay Campus, Bristol, BS16 1QY,
    - United Kingdom.
email: james2.huxtable@uwe.ac.uk



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: James Huxtable
    position: Da Man!
    text: I am a keen and passionate games developer, whose love of programming extends to mentoring others to allow them to develop games for themselves.
    img: profile_1.jpg
    social:
      - title: envelope #use for email address
        url: mailto:james2.huxtable@uwe.ac.uk
      - title: twitter
        url: http://twitter.com/HuxyUK
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Those who can do and those who can't teach games design."
